### ISSUE TITLE
Sync MongoDB.app version with MongoDB's server version

### ISSUE THREAD

**Issue by gcollazo** [gcollazo/mongodbapp#1]
Is this a good idea?

**Comment by froi** [comment]
Are you going to make a release every time they update MongoDB? If not I wouldn't worry about it. If you are then this makes sense.

**Comment by gcollazo** [comment]
The plan is to keep the MongoDB binaries version as close to the latest production version as possible.

**Comment by gcollazo** [comment]
Decided to sync this project's version with the version of the embedded MongoDB binaries.
