### ISSUE TITLE
Stop using Documents directory

### ISSUE THREAD

**Issue by kdubb** [gcollazo/mongodbapp#12]
Newer macOS installs synchronize the `Documents` directory to iCloud.  Running `mongoDB.app` on this configuration causes endless sync's to iCloud.

Considering the ephemeral nature of data files related to this type of application, which is indeed most used to ease development, moving them to `~/Application Support/mongoDB/` would seem more fitting.  This directory is permanent and suggested by Apple as the location for _internal_ application files.

**Comment by juliangrigera** [comment]
Hey @kdubb, check out the other issue, which asks for users to define their own directory. I created a PR addressing this issue (motivated by the macOS behavior you mention, BTW), but the default remains in the Documents folder. If @gcollazo agrees I could change this default to the one you suggest.

**Comment by kdubb** [comment]
I see the value in #8 / #11. At the same time... the default should work well with a _default_ macOS installation. I love the ease of use with `Postgres.app` no buttons to push, knobs to turn... it always "just works" without me remembering.   I'll submit a PR for the 1 line change that switches from `Documents` to `~/Library/Application Support`. Although, I'd love to see #11 merged as well.

**Comment by kdubb** [comment]
@juliangrigera It turned out to be that I made more than a "1 line change" lol.  The changes should still be compatible with your custom config file support.

**Comment by juliangrigera** [comment]
@kdubb yes, I peeked at the code, nice job! Hope it gets merged, as I said, iCloud synced Documents folder is the main reason I wanted custom settings.

**Comment by gcollazo** [comment]
Thanks!
