### ISSUE TITLE
Unable to update the app

### ISSUE THREAD

**Issue by kranack** [gcollazo/mongodbapp#14]
I'm using this application for a while now and I've never experienced this problem until now.
I can't update my app from the software update, the update download goes right but when I click on the "Install and Relaunch" button, it tells me an error occured while extracting the archive. I don't understand what's going wrong with it.

-----------------------
OS : OSX v 10.12.6 (Sierra)
Screenshots:
![capture d ecran 2017-11-10 a 14 30 19](https://user-images.githubusercontent.com/2787828/32660778-7081a99a-c624-11e7-881c-05f738b4abf3.png)
![capture d ecran 2017-11-10 a 14 30 33](https://user-images.githubusercontent.com/2787828/32660779-70962dd4-c624-11e7-8c62-869240aee250.png)
-----------------------

I don't know if the problem comes from my mac or from the application, nevermind I just post it there if anyone experienced it or has a explanation for this error :)

**Comment by gcollazo** [comment]
This should be fixed

**Comment by kranack** [comment]
Well done, the update from v4.0.0 to v.4.0.1 worked perfectly.

Thanks a lot !

**Comment by amcgregor** [comment]
Alas, does not appear to be fixed.  MongoDB.app version 4.0.8-build.1 (📆 ©2015!) fails to update to 4.2.0-build.3, same symptom as screenshots, [but this time in video form](http://s.webcore.io/bedd25752d54/2019-10-22--14-51-19--update-failure.mov).

**Comment by gcollazo** [comment]
Seems like the only solution is to download the newest binary manually and replace the old one. Future updates should upgrade properly.
