### ISSUE TITLE
Allow users to run different versions of Mongo

### ISSUE THREAD

**Issue by josemando** [gcollazo/mongodbapp#20]
The idea is to follow the same path of Postgres.app, where it has been possible for some time (I believe since the release of version 2) to have different versions of PostgreSQL in the same Postgres.app installation.

Here's a screenshot for those not familiar with Postgres.app
![postgresapp](https://user-images.githubusercontent.com/946167/42292126-97254584-7fa6-11e8-8c15-c8b44b987193.png)

**Comment by gcollazo** [comment]
I guess it would be doable but it will require a significant effort to achieve. I'm not opposed to the idea and encourage you or any other contributor to take a stab at implementing it. I don't have the time for such a big feature.

In the mean time you can just download the versions you want to use from https://github.com/gcollazo/mongodbapp/releases and rename them to match the version number and just run the one you need.

I will leave this issue open to signal potential contributors.
