### ISSUE TITLE
open mongo Connection refused 

### ISSUE THREAD

**Issue by wahello** [gcollazo/mongodbapp#21]
MongoDB shell version v4.0.0
connecting to: mongodb://127.0.0.1:27017
2018-07-18T09:56:02.127+0800 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:6
exception: connect failed

**Comment by gcollazo** [comment]
@keyeMyria I can't reproduce this error. Can you provide more context?

**Comment by wahello** [comment]
The data created when the version is 3.4 or older, so, need to do some extra actions. First start mongodbapp 3.6, execute
 ` db.adminCommand( { setFeatureCompatibilityVersion: "3.6" } )`
then start mongoapp 4.0. 

for 4.0 features, execute 

`db.adminCommand( { setFeatureCompatibilityVersion: "4.0" } )`
It fixed, Thanks.
