### ISSUE TITLE
Consider Cask Rename

### ISSUE THREAD

**Issue by ghost** [gcollazo/mongodbapp#22]
As there's no current brew package for "mongodb" Homebrew CLI drunkenly offers to install this Cask which looks more or less official until one visits the MongoDB installation instructions online to find out its not. As a result of this I propose your download result in quite a bit of lost Dev time setting up Mongo on a Mac. Would you agree?

If you agree, please consider renaming this cask to something other than "mongodb" or add a way to quickly communicate to users upon installation this is not an official app. Otherwise, perhaps we can leave this issue open for visibility. And if not no sweat.

Thanks.

**Comment by gcollazo** [comment]
Thanks for opening the issue. This feels like a Homebrew issue. You should consider opening an issue on their repo or submitting a change to the [cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mongodb.rb).

For my part I'm ok with changing the homebrew cask name to something like `mongodb-app`

**Comment by ghost** [comment]
Done https://github.com/Homebrew/homebrew-cask/issues/71503

**Comment by ghost** [comment]
Ref https://github.com/Homebrew/homebrew-cask/pull/71506 with new cask name chosen by those hombres

**Comment by ghost** [comment]
Root cause of issue: OSI https://writing.kemitchell.com/2019/06/13/SSPL-Not-Commons-Clause.html
