### ISSUE TITLE
Include MongoDB database tools

### ISSUE THREAD

**Issue by marek-benes** [gcollazo/mongodbapp#24]
Please include _mongorestore_ and _mongodump_ tools.

**Comment by gcollazo** [comment]
They are included

**Comment by stefanwascoding** [comment]
@gcollazo Where?
For me `/Applications/MongoDB.app/Contents/Resources/Vendor/mongodb/bin` of _7.0.3-build.2_ includes:
```
install_compass
mongod
mongos
```
Using `find` in the .app bundle, I could not find `mongorestore` or `mongodump`.
