### ISSUE TITLE
Upgrade MongoDB to 3.0

### ISSUE THREAD

**Issue by gcollazo** [gcollazo/mongodbapp#3]
MongoDB [announced](http://www.mongodb.com/blog/post/announcing-mongodb-30) they will be releasing version 3.0 of the database in March. I expect to upgrade the bundled version as soon as a stable version is available [here](https://www.mongodb.org/downloads).

**Comment by froi** [comment]
Awesomeness.

**Comment by gcollazo** [comment]
Done!
