### ISSUE TITLE
Mongo 3.0.3?

### ISSUE THREAD

**Issue by wavded** [gcollazo/mongodbapp#6]
Can a new version be released to support?

**Comment by gcollazo** [comment]
Yes! I'll do it this week. Hopefully tonight.

**Comment by gcollazo** [comment]
@wavded just published an update. You can just click on the "Check for Updates..." menu item and it will download and install.

![screen shot 2015-05-20 at 3 50 18 pm](https://cloud.githubusercontent.com/assets/61048/7734957/f887edd6-ff07-11e4-96fb-a2f1dc714367.png)

**Comment by wavded** [comment]
thx @gcollazo !
