### ISSUE TITLE
Menu bar icon invisible.

### ISSUE THREAD

**Issue by arjunmayilvaganan** [gcollazo/mongodbapp#7]
![screen 2016-01-04 at 6 24 18 pm](https://cloud.githubusercontent.com/assets/6371303/12090005/a51f347a-b310-11e5-895b-9c1281129e22.png)

![screen 2016-01-04 at 6 24 27 pm](https://cloud.githubusercontent.com/assets/6371303/12090007/b1d13f42-b310-11e5-8f99-9a2853487137.png)

Icon staying invisible unless clicked upon. Is there a workaround?

**Comment by gcollazo** [comment]
Fixed by 377e8c3.

**Comment by gcollazo** [comment]
@arjunmayilvaganan thanks for reporting I'll try to push an update soon.

**Comment by arjunmayilvaganan** [comment]
Thank you @gcollazo 
Thanks for this application. Saves me a lot of time.

**Comment by arjunmayilvaganan** [comment]
The app is easily discoverable through search engines, already. But, please do consider having a standalone domain/site for the app.

**Comment by gcollazo** [comment]
@arjunmayilvaganan the update is out, you should be able to click on "Check for updates" to get the latest version.

<img width="307" alt="screen shot 2016-01-04 at 11 39 50 am" src="https://cloud.githubusercontent.com/assets/61048/12093201/f0924886-b2d7-11e5-9d8f-c96862bbeb48.png">

**Comment by arjunmayilvaganan** [comment]
@gcollazo Updated. Yes, looks fine now.
